---
- name: Add subscription
  ansible.builtin.command:
    cmd: >-
      {{ __suseconnect_subscribe_command }} {{ __command_args }}
  vars:
    __suseconnect_subscribe_command: >-
      {% if ansible_distribution == 'SL-Micro' and not __suseconnect_is_registercloudguest %}
        {{ __suseconnect_commands_dict.subscription.transactional }}
      {% else %}
        {{ __suseconnect_commands_dict.subscription.general }}
      {% endif %}
    __command_args: >-
      -p {{ [item['product'],
          item['version'] | default(ansible_distribution_version),
          item['arch'] | default(ansible_machine)]
          | join('/')
      }}
      {% if item['key'] is defined %}
        -r {{ item['key'] }}
      {% endif %}{%- if item['email'] is defined %} -e {{ item['email'] }}
      {% endif %}
  when:
    - item['version'] == ansible_distribution_version
    - (__suseconnect_status[item['product']] is not defined or
      __suseconnect_status[item['product']]['status'] != 'Registered' or
      (item['version'] is defined and __suseconnect_status[item['product']]['version'] | string != item['version'] | string)) or
      suseconnect_reregister
  loop: "{{ suseconnect_subscriptions }}"
  loop_control:
    label: "{{ item['product'] }}"
  register: __suseconnect_subscribe_result
  changed_when: "__suseconnect_subscribe_result.rc == 0"
  no_log: "{{ 'true' if item['key'] is defined else 'false' }}"
