---
- name: Ensure required packages are installed
  ansible.builtin.package:
    name: "{{ required_packages }}"
    state: present

- name: Check instance type and fail if PAYG to prevent improper registration
  ansible.builtin.command: instance-flavor-check
  register: instance_flavor_result
  changed_when: false
  failed_when: instance_flavor_result.stdout.strip() == "PAYG"

- name: Determine if system is registercloudguest and set flag
  when:
    - not __suseconnect_is_registercloudguest is defined
  block:
    - name: Check if registercloudguest exists in /sbin
      ansible.builtin.stat:
        path: /sbin/registercloudguest
      register: __registercloudguest_stat

    - name: Set flag if registercloudguest exists
      ansible.builtin.set_fact:
        __suseconnect_is_registercloudguest: "{{ __registercloudguest_stat.stat.exists }}"

# add support for adding modules for transactional update.
