---
- name: Remove Subscriptions
  ansible.builtin.command: |
    {{ remove_subscription }} -d -p
    "{{- item['key'] | default(ansible_distribution) }}/
    {{- item['value']['version'] | default(ansible_distribution_version) }}/
    {{- item['value']['arch'] | default(ansible_machine) }}"
  vars:
    remove_subscription: >-
      {% if ansible_distribution == 'SL-Micro' and not __suseconnect_is_registercloudguest %}
        transactional-update register
      {% else %}
        /usr/sbin/SUSEConnect
      {% endif %}
  when:
    - suseconnect_remove_subscriptions | bool
    - item['key'] not in suseconnect_product_list
    - suseconnect_product_list | length > 0
    - item['value']['status'] == 'Registered'
    - item['key'] not in ['SLES', 'SL-Micro']
  with_dict: "{{ suseconnect_status }}"
  changed_when: false

- name: Deregister system
  ansible.builtin.command: |
    {{ deregister_command }}
  vars:
    deregister_command: >-
      {% if ansible_distribution == 'SL-Micro' and not __suseconnect_is_registercloudguest %}
        transactional-update register -d
      {% elif __suseconnect_is_registercloudguest %}
        registercloudguest --clean
      {% else %}
        /usr/sbin/SUSEConnect -d
      {% endif %}
  when:
    - suseconnect_product_list | length == 0
    - suseconnect_status.get('SLES', {}).get('status', 'Not Registered') != 'Not Registered' or
      suseconnect_status.get('SL-Micro', {}).get('status', 'Not Registered') != 'Not Registered'
  changed_when: false
