---
- name: Deregister system
  ansible.builtin.command:
    cmd: >-
      {{ __suseconnect_deregister_command }}
  when:
    - item['key'] == (ansible_distribution)
    - item['value']['status'] != 'Not Registered'
  loop: "{{ __suseconnect_status | dict2items }}"
  loop_control:
    label: "{{ item['key'] }}"
  changed_when: false
