---
- name: Deregister system
  ansible.builtin.command:
    cmd: >-
      {{ __suseconnect_deregister_command }}
  when:
    - suseconnect_product_list | length == 0
    - __suseconnect_status.get('SLES', {}).get('status', 'Not Registered') != 'Not Registered' or
      __suseconnect_status.get('SL-Micro', {}).get('status', 'Not Registered') != 'Not Registered'
  changed_when: false
