---
- name: Run asserts and pre-checks
  ansible.builtin.include_tasks: prechecks.yml

- name: Register system
  ansible.builtin.include_tasks: register.yml
  when:
    - not __suseconnect_is_payg_instance
    - not suseconnect_deregister

- name: Remove subscriptions
  ansible.builtin.include_tasks: remove_subscriptions.yml
  when:
    - not __suseconnect_is_payg_instance
    - suseconnect_remove_subscriptions | bool

- name: Deregister system
  ansible.builtin.include_tasks: deregister.yml
  when:
    - not __suseconnect_is_payg_instance
    - suseconnect_deregister | bool
