---
- name: Run Asserts and Pre-checks
  ansible.builtin.include_tasks: prechecks.yml

- name: Register system
  ansible.builtin.include_tasks: register.yml

- name: Deregister system
  ansible.builtin.include_tasks: deregister.yml
