---
- name: Run asserts and pre-checks
  ansible.builtin.include_tasks: prechecks.yml

- name: Register system
  when:
    - not __suseconnect_is_payg_instance
    - not suseconnect_deregister
  ansible.builtin.include_tasks: register.yml

- name: Manage subscriptions
  when:
    - not __suseconnect_is_payg_instance
    - suseconnect_subscriptions | selectattr('product', 'defined') | list | length > 0
  ansible.builtin.include_tasks: manage-subscriptions.yml

- name: Deregister system
  when:
    - not __suseconnect_is_payg_instance
    - suseconnect_deregister | bool
  ansible.builtin.include_tasks: deregister.yml
