---
- name: Run asserts and pre-checks
  ansible.builtin.include_tasks: prechecks.yml

- name: Register system
  ansible.builtin.include_tasks: register.yml
  when:
    - not __suseconnect_is_payg_instance
    - not suseconnect_deregister

- name: Manage subscriptions
  ansible.builtin.include_tasks: manage-subscriptions.yml
  when:
    - not __suseconnect_is_payg_instance
    - suseconnect_subscriptions is defined and suseconnect_subscriptions | selectattr('name', 'defined') | list | length > 0

- name: Deregister system
  ansible.builtin.include_tasks: deregister.yml
  when:
    - not __suseconnect_is_payg_instance
    - suseconnect_deregister | bool
