---
- name: Set subscription command for add or remove
  ansible.builtin.set_fact:
    subscribe_command: >-
      {% if ansible_distribution == 'SL-Micro' and not __suseconnect_is_registercloudguest %}
        transactional-update register
      {% else %}
        /usr/sbin/SUSEConnect
      {% endif %}

- name: Add subscription
  ansible.builtin.command: |
    {{ subscribe_command }}
    -p {{ item['product'] | default(ansible_distribution) }}/
    {{- item['version'] | default(ansible_distribution_version) }}/
    {{- item['arch'] | default(ansible_machine) }}
    {%- if item['key'] is defined %} -r {{ item['key'] }}{% endif %}
  when:
    - item['product'] not in ['SLES', 'SL-Micro']
  with_items: "{{ suseconnect_products }}"
  changed_when: false

- name: Remove Subscriptions
  ansible.builtin.command: |
    {{ subscribe_command }}
    -d -p "{{- item['key'] | default(ansible_distribution) }}/
    {{- item['value']['version'] | default(ansible_distribution_version) }}/
    {{- item['value']['arch'] | default(ansible_machine) }}"
  when:
    - suseconnect_remove_subscriptions | bool
    - item['key'] not in suseconnect_product_list
    - suseconnect_product_list | length > 0
    - item['value']['status'] == 'Registered'
    - item['key'] not in ['SLES', 'SL-Micro']
  with_dict: "{{ suseconnect_status }}"
  changed_when: false
