---
- name: Register SLES system
  ansible.builtin.command: |
    {{ item_binary }}
    {%- if item['key'] is defined %} -r {{ item['key'] }}{% endif %}
    {%- if item['email'] is defined %} -e {{ item['email'] }}{% endif %}
  vars:
    item_binary: >-
      {% if __suseconnect_is_registercloudguest %}
        registercloudguest
      {% else %}
        /usr/sbin/SUSEConnect
      {% endif %}
  when:
    - ansible_distribution == 'SLES'
    - ( suseconnect_status[item['product'] | default(ansible_distribution)] is not defined or
      ( suseconnect_status[item['product'] | default(ansible_distribution)]['status'] != 'Registered' or
      ( item['version'] is defined and suseconnect_status[item['product'] | default(ansible_distribution)]['version']|string != item['version']|string ))) or
      suseconnect_reregister
  with_items: "{{ suseconnect_products | selectattr('product', 'equalto', 'SLES') | list }}"
  changed_when: false

- name: Register SL-Micro system
  ansible.builtin.command: |
    {{ item_binary }}
    {%- if item['key'] is defined %} -r {{ item['key'] }}{% endif %}
    {%- if item['email'] is defined %} -e {{ item['email'] }}{% endif %}
  vars:
    item_binary: >-
      {% if __suseconnect_is_registercloudguest %}
        registercloudguest
      {% else %}
        transactional-update register
      {% endif %}
  when:
    - ansible_distribution == 'SL-Micro'
    - ( suseconnect_status[item['product'] | default(ansible_distribution)] is not defined or
      ( suseconnect_status[item['product'] | default(ansible_distribution)]['status'] != 'Registered' or
      ( item['version'] is defined and suseconnect_status[item['product'] | default(ansible_distribution)]['version']|string != item['version']|string ))) or
      suseconnect_reregister
  with_items: "{{ suseconnect_products | selectattr('product', 'equalto', 'SL-Micro') | list }}"
  changed_when: false

- name: Add subscriptions
  ansible.builtin.command: |
    {{ subscribe_command }} -p
    {{ item['product'] | default(ansible_distribution) }}/
    {{- item['version'] | default(ansible_distribution_version) }}/
    {{- item['arch'] | default(ansible_machine) }}
    {%- if item['key'] is defined %} -r {{ item['key'] }}{% endif %}
  vars:
    subscribe_command: >-
      {% if ansible_distribution == 'SL-Micro' and not __suseconnect_is_registercloudguest %}
        transactional-update register
      {% else %}
        /usr/sbin/SUSEConnect
      {% endif %}
  when:
    - item['product'] not in ['SLES', 'SL-Micro']
    - ( suseconnect_status[item['product'] | default(ansible_distribution)] is not defined or
      ( suseconnect_status[item['product'] | default(ansible_distribution)]['status'] != 'Registered' or
      ( item['version'] is defined and suseconnect_status[item['product'] | default(ansible_distribution)]['version']|string != item['version']|string ))) or
      suseconnect_reregister
  with_items: "{{ suseconnect_products }}"
  changed_when: false
