---
- name: Register system
  ansible.builtin.command:
    cmd: >-
      {{ __suseconnect_register_command }} {{ __command_args }}
  vars:
    __command_args: >-
      {%- if item['key'] is defined %} -r {{ item['key'] }}
      {% endif %}{%- if item['email'] is defined %} -e {{ item['email'] }}
      {% endif %}
  when:
    - item['product'] in [ansible_distribution]
    - item['version'] == ansible_distribution_version
    - ( __suseconnect_status[item['product'] | default(ansible_distribution)] is not defined or
      ( __suseconnect_status[item['product'] | default(ansible_distribution)]['status'] != 'Registered' or
      ( item['version'] is defined and __suseconnect_status[item['product'] | default(ansible_distribution)]['version']|string != item['version']|string )))
      or suseconnect_reregister
  loop: "{{ suseconnect_base_product }}"
  loop_control:
    label: "{{ item['product'] }}"
  changed_when: false
  no_log: "{{ __suseconnect_no_log }}"

- name: Add subscription
  ansible.builtin.command:
    cmd: >-
      {{ __suseconnect_subscribe_command }} {{ __command_args }}
  vars:
    __command_args: >-
      -p {{ [item['product'],
          item['version'] | default(ansible_distribution_version),
          item['arch'] | default(ansible_machine)]
          | join('/')
      }}
      {% if item['key'] is defined %}
        -r {{ item['key'] }}
      {% endif %}{%- if item['email'] is defined %} -e {{ item['email'] }}
      {% endif %}
  when:
    - item['version'] == ansible_distribution_version
    - (__suseconnect_status[item['product']] is not defined or
      __suseconnect_status[item['product']]['status'] != 'Registered' or
      (item['version'] is defined and __suseconnect_status[item['product']]['version'] | string != item['version'] | string)) or
     suseconnect_reregister
  loop: "{{ suseconnect_subscriptions }}"
  loop_control:
    label: "{{ item['product'] }}"
  changed_when: false
  no_log: "{{ __suseconnect_no_log }}"
