---
- name: Remove Subscriptions
  ansible.builtin.command:
    cmd: >-
      {{ __suseconnect_subscribe_command }} {{ __command_args }}
  vars:
    __command_args: >-
      -d -p {{ [item['key'] | default(ansible_distribution),
          item['value']['version'] | default(ansible_distribution_version),
          item['value']['arch'] | default(ansible_machine)]
          | join('/') }}
  when:
    - item['key'] not in suseconnect_product_list
    - suseconnect_product_list | length > 0
    - item['value']['status'] == 'Registered'
    - item['key'] not in ['SLES', 'SL-Micro']
  loop: "{{ __suseconnect_status | dict2items }}"
  changed_when: false
