---
- name: Remove subscriptions
  ansible.builtin.command:
    cmd: >-
      {{ __suseconnect_subscribe_command }} {{ __command_args }}
  vars:
    __command_args: >-
      -d -p {{ [item['key'] | default(ansible_distribution),
          item['value']['version'] | default(ansible_distribution_version),
          item['value']['arch'] | default(ansible_machine)]
          | join('/') }}
  when:
    - item['key'] not in __suseconnect_subscriptions_list
    - item['key'] != (ansible_distribution)
    - __suseconnect_subscriptions_list | length > 0
    - item['value']['status'] == 'Registered'
  loop: "{{ __suseconnect_status | dict2items }}"
  loop_control:
    label: "{{ item['key'] }}"
  changed_when: false
  no_log: true
