---
name: Ansible Lint

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 2 1 * *"

  workflow_dispatch:

jobs:
  ansible_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: |
          pip3 install ansible==9.1.0
          pip3 install ansible-compat==4.1.10
          pip3 install ansible-core==2.16.2
          pip3 install ansible-lint==6.22.1

      - name: Run ansible-lint
        working-directory: ${{ github.workspace }}
        run: |
          ansible-lint -v
